version: '3'

networks:
    backend-network:

services:                            
    nginx-backend:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - .:/app  
        networks:
            - backend-network    
        extra_hosts:
            - host.docker.internal:host-gateway    
        depends_on:
            - php 
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        tty: true
        volumes:
            - .:/app
        working_dir: /app
        environment:
            - PHP_IDE_CONFIG=serverName=phonebook.loc
            - XDEBUG_MODES=develop,debug,coverage
            - REMOTE_HOST=host.docker.internal
            - REMOTE_PORT=9003
            - IDE_KEY=docker
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - backend-network   
        restart: always