version: '3'

networks:
    frontend-network:

services:                            
    nginx-frontend:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - 8081:80
        volumes:
            - .:/app  
        networks:
            - frontend-network    
        extra_hosts:
            - host.docker.internal:host-gateway    